// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wage.Data;

namespace Wage.Data.Migrations
{
    [DbContext(typeof(WageDbContext))]
    partial class WageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wage.Core.Entities.AccessLink", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AccessLinks");
                });

            modelBuilder.Entity("Wage.Core.Entities.GroupManager", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("BaseAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<bool>("ChkCouncil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("CouncilDate")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("ProfCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProfName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StartAt")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(4)")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("GroupManagers");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Active = true,
                            BaseAmount = "1000000",
                            ChkCouncil = false,
                            Month = "01",
                            ProfCode = "10",
                            ProfName = "فربد ساسانی",
                            StartAt = "1399/01/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 2m,
                            Active = true,
                            BaseAmount = "800000",
                            ChkCouncil = false,
                            Month = "01",
                            ProfCode = "11",
                            ProfName = "مهدی جلالی",
                            StartAt = "1399/01/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 3m,
                            Active = true,
                            BaseAmount = "500000",
                            ChkCouncil = false,
                            Month = "01",
                            ProfCode = "12",
                            ProfName = "محمد سرگزی",
                            StartAt = "1399/01/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 4m,
                            Active = true,
                            BaseAmount = "20000",
                            ChkCouncil = false,
                            Month = "02",
                            ProfCode = "10",
                            ProfName = "فربد ساسانی",
                            StartAt = "1399/02/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 5m,
                            Active = true,
                            BaseAmount = "5000",
                            ChkCouncil = false,
                            Month = "02",
                            ProfCode = "11",
                            ProfName = "مهدی جلالی",
                            StartAt = "1399/02/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 6m,
                            Active = true,
                            BaseAmount = "70000",
                            ChkCouncil = false,
                            Month = "02",
                            ProfCode = "12",
                            ProfName = "محمد سرگزی",
                            StartAt = "1399/02/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 7m,
                            Active = true,
                            BaseAmount = "1000000",
                            ChkCouncil = false,
                            Month = "07",
                            ProfCode = "10",
                            ProfName = "فربد ساسانی",
                            StartAt = "1399/07/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 8m,
                            Active = true,
                            BaseAmount = "800000",
                            ChkCouncil = false,
                            Month = "07",
                            ProfCode = "11",
                            ProfName = "مهدی جلالی",
                            StartAt = "1399/07/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 9m,
                            Active = true,
                            BaseAmount = "500000",
                            ChkCouncil = false,
                            Month = "07",
                            ProfCode = "12",
                            ProfName = "محمد سرگزی",
                            StartAt = "1399/07/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 10m,
                            Active = true,
                            BaseAmount = "145266",
                            ChkCouncil = false,
                            Month = "08",
                            ProfCode = "10",
                            ProfName = "فربد ساسانی",
                            StartAt = "1399/08/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 11m,
                            Active = true,
                            BaseAmount = "63000",
                            ChkCouncil = false,
                            Month = "08",
                            ProfCode = "11",
                            ProfName = "مهدی جلالی",
                            StartAt = "1399/08/01",
                            Year = "1399"
                        },
                        new
                        {
                            Id = 12m,
                            Active = true,
                            BaseAmount = "45000",
                            ChkCouncil = false,
                            Month = "08",
                            ProfCode = "12",
                            ProfName = "محمد سرگزی",
                            StartAt = "1399/08/01",
                            Year = "1399"
                        });
                });

            modelBuilder.Entity("Wage.Core.Entities.GroupManagerDetails", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("EntranceDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EntranceTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ExitTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("GroupManagerId")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("GroupManagerId");

                    b.ToTable("GroupManagerDetails");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Active = true,
                            EntranceDate = "1399/01/01",
                            EntranceTime = "06:00",
                            ExitTime = "19:30",
                            GroupManagerId = 1m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 2m,
                            Active = true,
                            EntranceDate = "1399/01/02",
                            EntranceTime = "08:00",
                            ExitTime = "15:00",
                            GroupManagerId = 1m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 3m,
                            Active = true,
                            EntranceDate = "1399/01/03",
                            EntranceTime = "08:00",
                            ExitTime = "10:00",
                            GroupManagerId = 1m,
                            IsOnline = true
                        },
                        new
                        {
                            Id = 4m,
                            Active = true,
                            EntranceDate = "1399/01/04",
                            EntranceTime = "06:40",
                            ExitTime = "10:00",
                            GroupManagerId = 1m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 5m,
                            Active = true,
                            EntranceDate = "1399/01/01",
                            EntranceTime = "08:00",
                            ExitTime = "10:00",
                            GroupManagerId = 2m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 6m,
                            Active = true,
                            EntranceDate = "1399/01/02",
                            EntranceTime = "09:00",
                            ExitTime = "09:30",
                            GroupManagerId = 2m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 7m,
                            Active = true,
                            EntranceDate = "1399/01/03",
                            EntranceTime = "08:30",
                            ExitTime = "14:50",
                            GroupManagerId = 2m,
                            IsOnline = true
                        },
                        new
                        {
                            Id = 8m,
                            Active = true,
                            EntranceDate = "1399/01/01",
                            EntranceTime = "08:00",
                            ExitTime = "11:00",
                            GroupManagerId = 3m,
                            IsOnline = true
                        },
                        new
                        {
                            Id = 9m,
                            Active = true,
                            EntranceDate = "1399/01/02",
                            EntranceTime = "08:00",
                            ExitTime = "11:00",
                            GroupManagerId = 3m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 10m,
                            Active = true,
                            EntranceDate = "1399/01/04",
                            EntranceTime = "09:00",
                            ExitTime = "09:30",
                            GroupManagerId = 3m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 11m,
                            Active = true,
                            EntranceDate = "1399/01/08",
                            EntranceTime = "08:00",
                            ExitTime = "10:00",
                            GroupManagerId = 1m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 12m,
                            Active = true,
                            EntranceDate = "1399/01/09",
                            EntranceTime = "08:00",
                            ExitTime = "15:00",
                            GroupManagerId = 1m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 13m,
                            Active = true,
                            EntranceDate = "1399/01/10",
                            EntranceTime = "08:00",
                            ExitTime = "10:00",
                            GroupManagerId = 1m,
                            IsOnline = true
                        },
                        new
                        {
                            Id = 14m,
                            Active = true,
                            EntranceDate = "1399/01/14",
                            EntranceTime = "08:00",
                            ExitTime = "10:00",
                            GroupManagerId = 1m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 15m,
                            Active = true,
                            EntranceDate = "1399/01/08",
                            EntranceTime = "08:00",
                            ExitTime = "10:00",
                            GroupManagerId = 2m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 16m,
                            Active = true,
                            EntranceDate = "1399/01/09",
                            EntranceTime = "08:00",
                            ExitTime = "11:30",
                            GroupManagerId = 2m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 17m,
                            Active = true,
                            EntranceDate = "1399/01/10",
                            EntranceTime = "08:30",
                            ExitTime = "14:50",
                            GroupManagerId = 2m,
                            IsOnline = true
                        },
                        new
                        {
                            Id = 18m,
                            Active = true,
                            EntranceDate = "1399/01/08",
                            EntranceTime = "08:00",
                            ExitTime = "11:00",
                            GroupManagerId = 3m,
                            IsOnline = true
                        },
                        new
                        {
                            Id = 19m,
                            Active = true,
                            EntranceDate = "1399/01/09",
                            EntranceTime = "08:00",
                            ExitTime = "11:00",
                            GroupManagerId = 3m,
                            IsOnline = false
                        },
                        new
                        {
                            Id = 20m,
                            Active = true,
                            EntranceDate = "1399/01/10",
                            EntranceTime = "09:00",
                            ExitTime = "11:00",
                            GroupManagerId = 3m,
                            IsOnline = false
                        });
                });

            modelBuilder.Entity("Wage.Core.Entities.GroupManagerSchedule", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("EntranceDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EntranceTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ExitTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("GroupManagerId")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("MinTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("GroupManagerId");

                    b.ToTable("GroupManagerSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Active = true,
                            EntranceDate = "1399/01/01",
                            EntranceTime = "08:00",
                            ExitTime = "12:00",
                            GroupManagerId = 1m,
                            IsOnline = true,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 2m,
                            Active = true,
                            EntranceDate = "1399/01/02",
                            EntranceTime = "08:00",
                            ExitTime = "16:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 3m,
                            Active = true,
                            EntranceDate = "1399/01/03",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 4m,
                            Active = true,
                            EntranceDate = "1399/01/04",
                            EntranceTime = "08:00",
                            ExitTime = "13:45",
                            GroupManagerId = 1m,
                            IsOnline = true,
                            MinTime = "05:45"
                        },
                        new
                        {
                            Id = 5m,
                            Active = true,
                            EntranceDate = "1399/01/05",
                            EntranceTime = "08:00",
                            ExitTime = "15:10",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "07:10"
                        },
                        new
                        {
                            Id = 6m,
                            Active = true,
                            EntranceDate = "1399/01/06",
                            EntranceTime = "08:00",
                            ExitTime = "16:30",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "08:30"
                        },
                        new
                        {
                            Id = 7m,
                            Active = true,
                            EntranceDate = "1399/01/07",
                            EntranceTime = "08:00",
                            ExitTime = "12:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "04:00"
                        },
                        new
                        {
                            Id = 8m,
                            Active = true,
                            EntranceDate = "1399/01/08",
                            EntranceTime = "08:00",
                            ExitTime = "16:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 9m,
                            Active = true,
                            EntranceDate = "1399/01/09",
                            EntranceTime = "08:00",
                            ExitTime = "13:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "05:00"
                        },
                        new
                        {
                            Id = 10m,
                            Active = true,
                            EntranceDate = "1399/01/10",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 11m,
                            Active = true,
                            EntranceDate = "1399/01/11",
                            EntranceTime = "08:00",
                            ExitTime = "15:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "07:00"
                        },
                        new
                        {
                            Id = 12m,
                            Active = true,
                            EntranceDate = "1399/01/12",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 13m,
                            Active = true,
                            EntranceDate = "1399/01/13",
                            EntranceTime = "08:00",
                            ExitTime = "14:20",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "06:20"
                        },
                        new
                        {
                            Id = 14m,
                            Active = true,
                            EntranceDate = "1399/01/14",
                            EntranceTime = "08:00",
                            ExitTime = "17:30",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "09:30"
                        },
                        new
                        {
                            Id = 15m,
                            Active = true,
                            EntranceDate = "1399/01/15",
                            EntranceTime = "08:00",
                            ExitTime = "14:30",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "06:30"
                        },
                        new
                        {
                            Id = 16m,
                            Active = true,
                            EntranceDate = "1399/01/16",
                            EntranceTime = "08:00",
                            ExitTime = "16:30",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 17m,
                            Active = true,
                            EntranceDate = "1399/01/17",
                            EntranceTime = "08:00",
                            ExitTime = "11:00",
                            GroupManagerId = 1m,
                            IsOnline = false,
                            MinTime = "03:00"
                        },
                        new
                        {
                            Id = 18m,
                            Active = true,
                            EntranceDate = "1399/01/01",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 19m,
                            Active = true,
                            EntranceDate = "1399/01/02",
                            EntranceTime = "08:00",
                            ExitTime = "16:00",
                            GroupManagerId = 2m,
                            IsOnline = true,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 20m,
                            Active = true,
                            EntranceDate = "1399/01/03",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 21m,
                            Active = true,
                            EntranceDate = "1399/01/04",
                            EntranceTime = "08:00",
                            ExitTime = "13:45",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "05:45"
                        },
                        new
                        {
                            Id = 22m,
                            Active = true,
                            EntranceDate = "1399/01/05",
                            EntranceTime = "08:00",
                            ExitTime = "15:10",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "07:10"
                        },
                        new
                        {
                            Id = 23m,
                            Active = true,
                            EntranceDate = "1399/01/06",
                            EntranceTime = "08:00",
                            ExitTime = "16:30",
                            GroupManagerId = 2m,
                            IsOnline = true,
                            MinTime = "08:30"
                        },
                        new
                        {
                            Id = 24m,
                            Active = true,
                            EntranceDate = "1399/01/07",
                            EntranceTime = "08:00",
                            ExitTime = "12:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "04:00"
                        },
                        new
                        {
                            Id = 25m,
                            Active = true,
                            EntranceDate = "1399/01/08",
                            EntranceTime = "08:00",
                            ExitTime = "16:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 26m,
                            Active = true,
                            EntranceDate = "1399/01/09",
                            EntranceTime = "08:00",
                            ExitTime = "13:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "05:00"
                        },
                        new
                        {
                            Id = 27m,
                            Active = true,
                            EntranceDate = "1399/01/10",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 28m,
                            Active = true,
                            EntranceDate = "1399/01/11",
                            EntranceTime = "08:00",
                            ExitTime = "15:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "07:00"
                        },
                        new
                        {
                            Id = 29m,
                            Active = true,
                            EntranceDate = "1399/01/12",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 30m,
                            Active = true,
                            EntranceDate = "1399/01/13",
                            EntranceTime = "08:00",
                            ExitTime = "14:20",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "06:20"
                        },
                        new
                        {
                            Id = 31m,
                            Active = true,
                            EntranceDate = "1399/01/14",
                            EntranceTime = "08:00",
                            ExitTime = "17:30",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "09:30"
                        },
                        new
                        {
                            Id = 32m,
                            Active = true,
                            EntranceDate = "1399/01/15",
                            EntranceTime = "08:00",
                            ExitTime = "14:30",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "06:30"
                        },
                        new
                        {
                            Id = 33m,
                            Active = true,
                            EntranceDate = "1399/01/16",
                            EntranceTime = "08:00",
                            ExitTime = "16:30",
                            GroupManagerId = 2m,
                            IsOnline = true,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 34m,
                            Active = true,
                            EntranceDate = "1399/01/17",
                            EntranceTime = "08:00",
                            ExitTime = "11:00",
                            GroupManagerId = 2m,
                            IsOnline = false,
                            MinTime = "03:00"
                        },
                        new
                        {
                            Id = 35m,
                            Active = true,
                            EntranceDate = "1399/01/01",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 36m,
                            Active = true,
                            EntranceDate = "1399/01/02",
                            EntranceTime = "08:00",
                            ExitTime = "16:00",
                            GroupManagerId = 3m,
                            IsOnline = true,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 37m,
                            Active = true,
                            EntranceDate = "1399/01/03",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 38m,
                            Active = true,
                            EntranceDate = "1399/01/04",
                            EntranceTime = "08:00",
                            ExitTime = "13:45",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "05:45"
                        },
                        new
                        {
                            Id = 39m,
                            Active = true,
                            EntranceDate = "1399/01/05",
                            EntranceTime = "08:00",
                            ExitTime = "15:10",
                            GroupManagerId = 3m,
                            IsOnline = true,
                            MinTime = "07:10"
                        },
                        new
                        {
                            Id = 40m,
                            Active = true,
                            EntranceDate = "1399/01/06",
                            EntranceTime = "08:00",
                            ExitTime = "16:30",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "08:30"
                        },
                        new
                        {
                            Id = 41m,
                            Active = true,
                            EntranceDate = "1399/01/07",
                            EntranceTime = "08:00",
                            ExitTime = "12:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "04:00"
                        },
                        new
                        {
                            Id = 42m,
                            Active = true,
                            EntranceDate = "1399/01/08",
                            EntranceTime = "08:00",
                            ExitTime = "16:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 43m,
                            Active = true,
                            EntranceDate = "1399/01/09",
                            EntranceTime = "08:00",
                            ExitTime = "13:00",
                            GroupManagerId = 3m,
                            IsOnline = true,
                            MinTime = "05:00"
                        },
                        new
                        {
                            Id = 44m,
                            Active = true,
                            EntranceDate = "1399/01/10",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 45m,
                            Active = true,
                            EntranceDate = "1399/01/11",
                            EntranceTime = "08:00",
                            ExitTime = "15:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "07:00"
                        },
                        new
                        {
                            Id = 46m,
                            Active = true,
                            EntranceDate = "1399/01/12",
                            EntranceTime = "08:00",
                            ExitTime = "17:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "09:00"
                        },
                        new
                        {
                            Id = 47m,
                            Active = true,
                            EntranceDate = "1399/01/13",
                            EntranceTime = "08:00",
                            ExitTime = "14:20",
                            GroupManagerId = 3m,
                            IsOnline = true,
                            MinTime = "06:20"
                        },
                        new
                        {
                            Id = 48m,
                            Active = true,
                            EntranceDate = "1399/01/14",
                            EntranceTime = "08:00",
                            ExitTime = "17:30",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "09:30"
                        },
                        new
                        {
                            Id = 49m,
                            Active = true,
                            EntranceDate = "1399/01/15",
                            EntranceTime = "08:00",
                            ExitTime = "14:30",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "06:30"
                        },
                        new
                        {
                            Id = 50m,
                            Active = true,
                            EntranceDate = "1399/01/16",
                            EntranceTime = "08:00",
                            ExitTime = "16:30",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "08:00"
                        },
                        new
                        {
                            Id = 51m,
                            Active = true,
                            EntranceDate = "1399/01/17",
                            EntranceTime = "08:00",
                            ExitTime = "11:00",
                            GroupManagerId = 3m,
                            IsOnline = false,
                            MinTime = "03:00"
                        });
                });

            modelBuilder.Entity("Wage.Core.Entities.Holiday", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("HolidayDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Active = true,
                            HolidayDate = "1399/01/12",
                            Note = "روز ج.ا"
                        },
                        new
                        {
                            Id = 2m,
                            Active = true,
                            HolidayDate = "1399/01/13",
                            Note = "روز درختکاری"
                        },
                        new
                        {
                            Id = 3m,
                            Active = true,
                            HolidayDate = "1399/01/25",
                            Note = "ولادت حضرت علی"
                        },
                        new
                        {
                            Id = 4m,
                            Active = true,
                            HolidayDate = "1399/07/03",
                            Note = "آلودگی هوا"
                        },
                        new
                        {
                            Id = 5m,
                            Active = true,
                            HolidayDate = "1399/07/03",
                            Note = "آلودگی هوا"
                        },
                        new
                        {
                            Id = 6m,
                            Active = true,
                            HolidayDate = "1399/07/10",
                            Note = "آلودگی هوا"
                        },
                        new
                        {
                            Id = 7m,
                            Active = true,
                            HolidayDate = "1399/07/27",
                            Note = "آلودگی هوا"
                        },
                        new
                        {
                            Id = 8m,
                            Active = true,
                            HolidayDate = "1399/08/01",
                            Note = "برف سنگین"
                        },
                        new
                        {
                            Id = 9m,
                            Active = true,
                            HolidayDate = "1399/08/19",
                            Note = "سقوط هواپیما"
                        },
                        new
                        {
                            Id = 10m,
                            Active = true,
                            HolidayDate = "1399/09/12",
                            Note = "برف سنگین"
                        },
                        new
                        {
                            Id = 11m,
                            Active = true,
                            HolidayDate = "1399/09/13",
                            Note = "برف سنگین"
                        },
                        new
                        {
                            Id = 12m,
                            Active = true,
                            HolidayDate = "1399/10/18",
                            Note = "آلودگی هوا"
                        },
                        new
                        {
                            Id = 13m,
                            Active = true,
                            HolidayDate = "1399/11/11",
                            Note = "آلودگی هوا"
                        },
                        new
                        {
                            Id = 14m,
                            Active = true,
                            HolidayDate = "1399/12/12",
                            Note = "آلودگی هوا"
                        });
                });

            modelBuilder.Entity("Wage.Core.Entities.Role", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Active = true,
                            DisplayName = "کاربر ارشد",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2m,
                            Active = true,
                            DisplayName = "کاربر",
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("Wage.Core.Entities.RoleAccess", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("AccessLinkId")
                        .HasColumnType("decimal(18,0)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("AccessLinkId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleAccesses");
                });

            modelBuilder.Entity("Wage.Core.Entities.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpireTime")
                        .HasColumnType("DateTime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Active = true,
                            FirstName = "میلاد",
                            LastName = "جلالی",
                            Password = "GEwa01iaRNvdbsOGhIFi4w==",
                            Username = "milad@gmail.com"
                        },
                        new
                        {
                            Id = 2m,
                            Active = true,
                            FirstName = "فربد",
                            LastName = "ساسانی",
                            Password = "GEwa01iaRNvdbsOGhIFi4w==",
                            Username = "feri@gmail.com"
                        },
                        new
                        {
                            Id = 3m,
                            Active = true,
                            FirstName = "رضا",
                            LastName = "عطاران",
                            Password = "GEwa01iaRNvdbsOGhIFi4w==",
                            Username = "reza@gmail.com"
                        });
                });

            modelBuilder.Entity("Wage.Core.Entities.UserRole", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("UserId")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Active = true,
                            RoleId = 1m,
                            UserId = 1m
                        },
                        new
                        {
                            Id = 2m,
                            Active = true,
                            RoleId = 2m,
                            UserId = 2m
                        });
                });

            modelBuilder.Entity("Wage.Core.Entities.GroupManagerDetails", b =>
                {
                    b.HasOne("Wage.Core.Entities.GroupManager", "GroupManager")
                        .WithMany("GroupManagerDetails")
                        .HasForeignKey("GroupManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wage.Core.Entities.GroupManagerSchedule", b =>
                {
                    b.HasOne("Wage.Core.Entities.GroupManager", null)
                        .WithMany("GroupManagerSchedules")
                        .HasForeignKey("GroupManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wage.Core.Entities.RoleAccess", b =>
                {
                    b.HasOne("Wage.Core.Entities.AccessLink", "AccessLink")
                        .WithMany("RoleAccesses")
                        .HasForeignKey("AccessLinkId");

                    b.HasOne("Wage.Core.Entities.Role", "Role")
                        .WithMany("RoleAccesses")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Wage.Core.Entities.UserRole", b =>
                {
                    b.HasOne("Wage.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("Wage.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
